const CategorizedWords = {
    Country: [
        'Argentina',
        'Australia',
        'Brazil',
        'Canada',
        'China',
        'Egypt',
        'France',
        'Germany',
        'India',
        'Italy',
        'Japan',
        'Kenya',
        'Mexico',
        'Netherlands',
        'Nigeria',
        'Russia',
        'South Korea',
        'Spain',
        'United Kingdom',
        'United States',
    ],
    Food: [
        'Pizza',
        'Sushi',
        'Burger',
        'Pasta',
        'Tacos',
        'Curry',
        'Salad',
        'Sandwich',
        'Steak',
        'Ramen',
        'Paella',
        'Pho',
        'Dumplings',
        'Burrito',
        'Lasagna',
        'Pancakes',
        'Chocolate',
        'Ice Cream',
        'Cheese',
        'Croissant',
    ],
    Suneung: [
        'Abate',
        'Benevolent',
        'Candid',
        'Deference',
        'Ebullient',
        'Fervent',
        'Garrulous',
        'Hackneyed',
        'Iconoclast',
        'Jubilant',
        'Keen',
        'Lament',
        'Magnanimous',
        'Nebulous',
        'Obfuscate',
        'Pensive',
        'Quaint',
        'Rancor',
        'Sagacious',
        'Taciturn',
    ],
};

export default CategorizedWords;
