const CategorizedWords = {
    Country: [
        'Argentina',
        'Australia',
        'Brazil',
        'Canada',
        'China',
        'Egypt',
        'France',
        'Germany',
        'India',
        'Italy',
        'Japan',
        'Kenya',
        'Mexico',
        'Netherlands',
        'Nigeria',
        'Russia',
        'South Korea',
        'Spain',
        'United Kingdom',
        'United States',
    ],
    Food: [
        'Pizza',
        'Sushi',
        'Burger',
        'Pasta',
        'Tacos',
        'Curry',
        'Salad',
        'Sandwich',
        'Steak',
        'Ramen',
        'Paella',
        'Pho',
        'Dumplings',
        'Burrito',
        'Lasagna',
        'Pancakes',
        'Chocolate',
        'Ice Cream',
        'Cheese',
        'Croissant',
    ],
    Suneung: [
        'Abate',
        'Benevolent',
        'Candid',
        'Deference',
        'Ebullient',
        'Fervent',
        'Garrulous',
        'Hackneyed',
        'Iconoclast',
        'Jubilant',
        'Keen',
        'Lament',
        'Magnanimous',
        'Nebulous',
        'Obfuscate',
        'Pensive',
        'Quaint',
        'Rancor',
        'Sagacious',
        'Taciturn',
    ],
    Idol: [
        'Newjeans',
        'Bts',
        'Riize',
        'Ive',
        'Aespa',
        'ILLIT',
        'I-DLE',
        'Seventeen',
        'LE SSERAFIM',
        'Blackpink',
        'Red Velvet',
        'Kiss of life',
        'Twice',
        'Viviz',
        'Bigbang',
        'TOMORROW X TOGETHER',
        'boynextdoor',
        'Stray Kids',
        'Itzy',
        'Beast',
    ],
    NEXT: [
        'Sua',
        'Dong Hyeok',
        'Tae Gyun',
        'Do Won',
        'Sang Woo',
        'Seong Min',
        'Se hyeon',
        'So Yun',
        'Ye Rang',
        'Eun Seong',
        'Jeong Hyeon',
        'Seong Hui',
        'Do Gyeong',
        'Hui jae',
        'Gyeong Bin',
        'So Jeong',
        'Ji Eun',
        'YeunJoon',
        'Ye Won',
        'Su Bin',
        'Hye yeong',
        'Hyeon Seong',
        'Won Gyeong',
        'So Yeong',
        'Min Ji',
    ],
};

export default CategorizedWords;
