const CategorizedWords = {
    Country: [
        'Argentina',
        'Australia',
        'Brazil',
        'Canada',
        'China',
        'Egypt',
        'France',
        'Germany',
        'India',
        'Italy',
        'Japan',
        'Kenya',
        'Mexico',
        'Netherlands',
        'Nigeria',
        'Russia',
        'South Korea',
        'Spain',
        'United Kingdom',
        'United States',
    ],
    Food: [
        'Pizza',
        'Sushi',
        'Burger',
        'Pasta',
        'Tacos',
        'Curry',
        'Salad',
        'Sandwich',
        'Steak',
        'Ramen',
        'Paella',
        'Pho',
        'Dumplings',
        'Burrito',
        'Lasagna',
        'Pancakes',
        'Chocolate',
        'Ice Cream',
        'Cheese',
        'Croissant',
    ],
    Suneung: [
        'gather',
        'material',
        'prescription',
        'assign',
        'skip',
        'loneliness',
        'knowledgeable',
        'fundamental',
        'force',
        'up to',
        'regular',
        'attract',
        'irrelevant',
        'include',
        'firm',
        'ecological',
        'solution',
        'responsibility',
        'comprehension',
    ],
    Idol: [
        'Newjeans',
        'Bts',
        'Riize',
        'Ive',
        'Aespa',
        'ILLIT',
        'I-DLE',
        'Seventeen',
        'LE SSERAFIM',
        'Blackpink',
        'Red Velvet',
        'Kiss of life',
        'Twice',
        'Viviz',
        'Bigbang',
        'TOMORROW X TOGETHER',
        'boynextdoor',
        'Stray Kids',
        'Itzy',
        'Beast',
    ],
    NEXT: [
        'Sua',
        'Dong Hyeok',
        'Tae Gyun',
        'Do Won',
        'Sang Woo',
        'Seong Min',
        'Se hyeon',
        'So Yun',
        'Ye Rang',
        'Eun Seong',
        'Jung Hyeon',
        'Seong Hui',
        'Do Gyeong',
        'Hui jae',
        'Gyeong Bin',
        'So Jeong',
        'Ji Eun',
        'YeunJoon',
        'Ye Won',
        'Su Bin',
        'Hye yeong',
        'Hyeon Seong',
        'Won Gyeong',
        'So Yeong',
        'Min Ji',
        'Boreum',
        'Sang Hyeon',
        'Hyeok jun',
        'Yeong Chan',
        'Hong Gyu',
        'Do Hyeon',
        'Seok Min',
        'Yeong Heon',
        'Yu Cheol',
        'Jae yun',
        'Cheol jong',
        'Yu Bin',
        'Ha Yeong',
    ],
};

export default CategorizedWords;
